#### Numpy Library
- Processing N-Dimensional Arrays

In [43]:
import numpy as np

li = [1,2,3,'z']

a = np.array(li)

b = np.arange(15)

a
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
rn = np.random.randint(0,1,size=10)
rn1 = np.random.randint(0,2,size=(3,3))
rn2 = np.random.randint(0,2,size=(3,3,3,3))
#rn2[2][2][2][1]
rn1

array([[1, 0, 1],
       [1, 1, 0],
       [0, 0, 0]])

In [44]:
rn2.ndim
rn2.size
rn2.shape
rn2.dtype
rn2.itemsize
rn2.nbytes

324

In [53]:
rn1 = np.random.randint(1,20,size=(3,3))
rn1


array([[ 6, 17,  3],
       [ 5,  6,  9],
       [18,  5,  5]])

In [67]:
c = b.reshape(5,3)

In [68]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [72]:
d = c+2
d

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [ ]:
# 2D Array Matrix
import numpy as np

mat_a = [[0,1,2],[3,4,5],[6,7,8]]
mat_b = [[1,2,3],[1,2,3],[1,2,3]]

def get_col(matrix,row):
    return matrix[row]
def get_column(matrix,column_number):
    column = []
    for i in range(len(matrix)):
        

#### Pandas
**Use Cases**
- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- Series
- DataFrames
 

In [79]:
import pandas as pd

internal1 = {'s1':21,'s2':18,'s3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':11,'s2':14,'s3':25}

internal2 = pd.Series(internal2)

print(internal2)
print(internal1)

s1    11
s2    14
s3    25
dtype: int64
s1    21
s2    18
s3    24
dtype: int64


In [85]:
final = {'internal1':internal1,'internal2':internal2}
final = pd.DataFrame(final)
final['internal1']

s1    21
s2    18
s3    24
Name: internal1, dtype: int64

In [86]:
final

internal1  internal2
s1         21         11
s2         18         14
s3         24         25

In [87]:
final.columns # Names of all Columns

Index(['internal1', 'internal2'], dtype='object')

In [90]:
final.values # Lists of all Rows

array([[21, 11],
       [18, 14],
       [24, 25]], dtype=int64)

In [91]:
final.values[2]

array([24, 25], dtype=int64)

In [94]:
final.values[2][0]
final.values[2,0]

24

In [97]:
for row in final.values:
    print('internal1 - ',row[0],',internal2 -', row[1] )
        

internal1 -  21 ,internal2 - 11
internal1 -  18 ,internal2 - 14
internal1 -  24 ,internal2 - 25


In [104]:
final.loc['s4'] =[16,22]
final

internal1  internal2
s1         21         11
s2         18         14
s3         24         25
3          15         18
s4         16         22

In [101]:
final

internal1  internal2
s1         21         11
s2         18         14
s3         24         25
3          15         18

In [110]:
final = final.drop(3)
final

internal1  internal2
s1         21         11
s2         18         14
s3         24         25
s4         16         22

In [113]:
final.values[3] = [14,25]

In [114]:
final

internal1  internal2
s1         21         11
s2         18         14
s3         22         22
s4         14         25

In [118]:
# Reading CSV file data
import pandas as pd
filepath ='Datafiles/income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [121]:
# Extract incomeof all states in 2013

# California : 57528

#incomedf.values

for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [123]:
# Average income of Arizona

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum//len(incomedf.values[2][2:])

47214

In [126]:
# Average income of all states in year 2012
sum =0
for row in incomedf.values:
    sum+=row[-2]
sum//len(incomedf.values)
    

50038